kind: pipeline
name: build-and-deploy

steps:
  - name: registry
    image: plugins/docker
    settings:
      registry: registry.wayy.fr
      repo: registry.wayy.fr/wayy/requestarr
      username:
        from_secret: quay_username
      password:
        from_secret: quay_password
      tags:
        - latest
        - ${DRONE_COMMIT_SHA:0:7}

  - name: docker
    image: plugins/docker
    settings:
      repo: wayytempest/requestarr
      dockerfile: Dockerfile
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - latest
        - ${DRONE_COMMIT_SHA:0:7}
